### ISSUE TITLE
npm install !== git clone

### ISSUE THREAD

**Issue by eldadj** [triniwiz/nativescript-sse#4]
Hi,

The source installed when doing 
`npm install nativescript-sse` and 
`git clone https://github.com/triniwiz/nativescript-sse.git`
are different.  The npm version is pure Javascript and the git clone version is Typescript. 

Also trying to use either doesn't work. Creating a new issue for that.

**Comment by 1u0n** [comment]
found the same problem, and same simple solution. This plugin's android version fails out of the box otherwise, which makes it difficult to depend on, isn't the repo creator active anymore?

**Comment by bradmartin** [comment]
Hi @eldadj -

The source is different on npm vs. git - because typescript can't be run anywhere. Only the transpiled .js files can actually execute. Does that make sense? So typically, if you're a good developer who cares about consumers 😄, you don't ship the typescript to npm because it's wasted files. The only TS file that should be in a npm module is a `.d.ts` file. So this package if you `clone` the repo - you'll need to transpile the .ts files into .js and then use the output .js files in your app.

Hope that makes sense 👍
